# cloudbuild.yaml
steps:
  # Get latest version tag
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git fetch --tags
        git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0" > current_version.txt
        echo "$(cat current_version.txt)"

  # Process PR labels and determine version type
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if PR_TYPE is empty array or not set
        if [ -z "$$_PR_TYPE" ] || [ "$$_PR_TYPE" = "[]" ]; then
          echo "timestamp" > version_type.txt
        else
          # Take first label from the array
          echo "$$_PR_TYPE" | tr '[],' '\n' | head -n 1 > version_type.txt
        fi

  # Bump version based on PR label or use timestamp
  - name: 'python:3.9'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import os
        import re
        from datetime import datetime

        def bump_version(current, bump_type):
            # Remove 'v' prefix if present
            current = current.lstrip('v')
            
            # If PR_TYPE is timestamp, use current version with timestamp
            if bump_type.lower() == 'timestamp':
                timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
                return f"v{current}-{timestamp}"
            
            # Regular semantic version bumping
            major, minor, patch = map(int, current.split('.'))
            
            if bump_type == 'major':
                major += 1
                minor = 0
                patch = 0
            elif bump_type == 'minor':
                minor += 1
                patch = 0
            else:  # patch
                patch += 1
                
            return f"v{major}.{minor}.{patch}"

        # Read current version
        with open('current_version.txt', 'r') as f:
            current_version = f.read().strip()

        # Read version type from file
        with open('version_type.txt', 'r') as f:
            bump_type = f.read().strip()

        # Calculate new version
        new_version = bump_version(current_version, bump_type)

        # Save new version
        with open('new_version.txt', 'w') as f:
            f.write(new_version)
            
        # Save whether this is a semantic version for later use
        is_semantic = bump_type.lower() in ['major', 'minor', 'patch']
        with open('is_semantic.txt', 'w') as f:
            f.write(str(is_semantic).lower())
            
        print(f"Version update: {current_version} -> {new_version}")

  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Build the Vite app
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Create tar archive of dist directory
  - name: 'ubuntu'
    args: ['tar', '-czf', 'release.tar.gz', '-C', 'dist', '.']

  # Create GitHub release with new version
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    secretEnv: ['GITHUB_TOKEN']
    args:
      - '-c'
      - |
        NEW_VERSION=$(cat new_version.txt)
        IS_SEMANTIC=$(cat is_semantic.txt)

        # Set draft status based on whether this is a semantic version
        if [ "$${IS_SEMANTIC}" = "true" ]; then
          DRAFT="false"
        else
          DRAFT="true"
        fi

        curl -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/ranson21/portfolio-web/releases \
          -d '{
            "tag_name": "'$${NEW_VERSION}'",
            "name": "Release '$${NEW_VERSION}'",
            "body": "Release version '$${NEW_VERSION}'",
            "draft": '$${DRAFT}',
            "prerelease": false
          }' > release.json

        # Extract release id
        RELEASE_ID=$(cat release.json | jq .id)

        # Upload asset
        curl -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Content-Type: application/gzip" \
          -H "Accept: application/vnd.github.v3+json" \
          --data-binary @release.tar.gz \
          "https://uploads.github.com/repos/ranson21/portfolio-web/releases/$${RELEASE_ID}/assets?name=release.tar.gz"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: 'GITHUB_TOKEN'

substitutions:
  _PR_TYPE: '' # This will now be populated by the PR label if it exists
