steps:
  # Get latest version
  - name: 'us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder'
    args: ['--action', 'get-version', '--repo-owner', '${_REPO_OWNER}', '--repo-name', 'portfolio-web']
    secretEnv: ['GITHUB_TOKEN']
    id: 'get-version'
    github:
      name: 'Get Latest Version'
      status: 'pending'

  # Process PR info and bump version
  - name: 'us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Debug environment variables:"
        echo "PR_TYPE value (should be commit SHA): ${_PR_TYPE}"
        echo "IS_MERGE value: ${_IS_MERGE}"

        VERSION_TYPE="${_PR_TYPE}"
        if [ -z "${_PR_TYPE}" ]; then
          VERSION_TYPE="timestamp"
        fi

        python /usr/local/bin/cli.py \
          --action bump-version \
          --repo-owner ${_REPO_OWNER} \
          --repo-name portfolio-web \
          --current-version "$$(cat current_version.txt)" \
          --version-type "$${VERSION_TYPE}" \
          --is-merge "${_IS_MERGE}" \
          --pr-number "${_PR_NUMBER}"
    secretEnv: ['GITHUB_TOKEN']
    id: 'bump-version'
    waitFor: ['get-version']
    github:
      name: 'Bump Version'
      status: 'pending'

  # Export version to environment
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "export const APP_VERSION = '$(cat new_version.txt)'" > src/version.js
    id: 'export-version'
    waitFor: ['bump-version']
    github:
      name: 'Export Version'
      status: 'pending'

  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    id: 'install'
    waitFor: ['bump-version']
    github:
      name: 'Install Dependencies'
      status: 'pending'

  # Build the Vite app
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build'
    waitFor: ['install']
    github:
      name: 'Build Vite App'
      status: 'pending'

  # Create tar archive of dist directory
  - name: 'ubuntu'
    args: ['tar', '-czf', 'release.tar.gz', '-C', 'dist', '.']
    id: 'create-tar'
    waitFor: ['build']
    github:
      name: 'Create Release Archive'
      status: 'pending'

  # Debug step
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Files after bump-version:"
        ls -la
        echo "Content of new_version.txt (if exists):"
        find / -name new_version.txt 2>/dev/null || echo "File not found"
    waitFor: ['create-tar']
    id: 'debug'
    github:
      name: 'Debug Check'
      status: 'pending'

  # Create GitHub release
  - name: 'us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Content of new_version.txt: $(cat new_version.txt)"
        VERSION=$(cat new_version.txt)
        if [[ "${_IS_MERGE}" != "true" ]]; then
          python /usr/local/bin/cli.py \
            --action create-release \
            --repo-owner ${_REPO_OWNER} \
            --repo-name portfolio-web \
            --current-version "$${VERSION}" \
            --is-draft
        else
          python /usr/local/bin/cli.py \
            --action create-release \
            --repo-owner ${_REPO_OWNER} \
            --repo-name portfolio-web \
            --current-version "$${VERSION}"
        fi
    secretEnv: ['GITHUB_TOKEN']
    id: 'create-release'
    waitFor: ['create-tar']
    github:
      name: 'Create GitHub Release'
      status: 'pending'

  # Update parent repo submodule
  - name: 'us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder'
    args:
      [
        '--action',
        'update-submodule',
        '--repo-owner',
        '${_REPO_OWNER}',
        '--repo-name',
        'portfolio-web',
        '--parent-repo',
        'portfolio',
        '--submodule-path',
        'apps/web/portfolio',
        '--current-version',
        '$$(cat new_version.txt)',
        '--is-merge',
        '${_IS_MERGE}',
      ]
    secretEnv: ['GITHUB_TOKEN']
    id: 'update-submodule'
    waitFor: ['create-release']
    github:
      name: 'Update Parent Repo Submodule'
      status: 'pending'

options:
  status:
    - context: 'Get Latest Version'
      id: 'get-version'
    - context: 'Bump Version'
      id: 'bump-version'
    - context: 'Export Version'
      id: 'export-version'
    - context: 'Install Dependencies'
      id: 'install'
    - context: 'Build Vite App'
      id: 'build'
    - context: 'Create Release Archive'
      id: 'create-tar'
    - context: 'Debug Check'
      id: 'debug'
    - context: 'Create GitHub Release'
      id: 'create-release'
    - context: 'Update Parent Repo Submodule'
      id: 'update-submodule'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: 'GITHUB_TOKEN'

substitutions:
  _PR_TYPE: '' # Populated by the PR label if it exists
  _REPO_OWNER: ''
  _IS_MERGE: 'false'
  _PR_NUMBER: ''
